### ISSUE TITLE
Card Images error on svg images

### ISSUE THREAD

**Issue by ahmadou5** [ahmadou5/Hawks#18]
when you add an svg image type on the img src it happens to break or zooms in the images on mobile devices check on this

**Comment by getlost01** [comment]
Please elaborate, on what the exact issue is with the some images.

**Comment by ahmadou5** [comment]
This is what shown on mobile phone after production:

![IMG_0442](https://github.com/ahmadou5/Hawks/assets/78315869/4add9e15-f4e5-4b2f-a79c-4f81de95d250)
 
 This is what is expected to be shown(development ): 
![e0d8b1f9-7b22-4dea-8c32-a7ae0b5ff64a](https://github.com/ahmadou5/Hawks/assets/78315869/2287f27c-8411-41e2-9042-f1769cfaf9ad)

**Comment by getlost01** [comment]
### Hi, I have tested this on my phone it is showing it like normal.
<br/>
<img height="720" src="https://github.com/ahmadou5/Hawks/assets/79409258/7a152b72-c5ab-420f-afc9-982993edebd4"/>
