### ISSUE TITLE
Connect with Github Integration

### ISSUE THREAD

**Issue by ahmadou5** [ahmadou5/Hawks#29]
### Description

Create a Sign in with gihub functionality and add it to the sign in button 

### Do you want to work on this issue?

No

**Comment by harshsharma-11** [comment]
I am ready to work ,.....
i am working on it

**Comment by ahmadou5** [comment]
Okay Just start working on it

**Comment by ahmadou5** [comment]
Yeah as I merge your pull requests it will count
